name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Ensure you deploy from the correct branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Move to React Project Folder
      run: cd breac-webiste  # Replace this with the actual folder name if your project is inside a subfolder

    - name: Install and Build
      run: |
        npm install
        npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./breac-webiste/build  # Make sure this points to the correct build folder
